CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer(
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMER_NAME VARCHAR(50),
    CUSTOMER_AGE INT
);

CREATE TABLE `Order`(
	ORDER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    ORDER_TOTAL_PRICE FLOAT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer (CUSTOMER_ID)
);

CREATE TABLE Product(
    PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRODUCT_Name VARCHAR(50),
    PRODUCT_Price FLOAT
);

CREATE TABLE OrderDetail(
	ORDER_ID INT,
    PRODUCT_ID INT,
    odQTY VARCHAR(100),
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES `Order` (ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES Product (PRODUCT_ID)
);