CREATE DATABASE QuanLyVatTu;
USE QuanLyVatTu;
CREATE TABLE PhieuXuat(
	SoPX INT PRIMARY KEY AUTO_INCREMENT,
    NgayXuat DATE
);

CREATE TABLE VatTu(
	MaVTU INT PRIMARY KEY AUTO_INCREMENT,
    TenVTU VARCHAR(50)
);

CREATE TABLE PhieuNhap(
	SoPN INT PRIMARY KEY AUTO_INCREMENT,
    NgayNhap DATE
);

CREATE TABLE DonDH(
	SoDH INT PRIMARY KEY AUTO_INCREMENT,
    NgayDH DATE,
    MaNCC INT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC (MaNCC)
);

CREATE TABLE NhaCC(
	MaNCC INT PRIMARY KEY AUTO_INCREMENT,
    TenNCC VARCHAR(50),
    DiaChi VARCHAR(50)
);

CREATE TABLE ChiTietPhieuXuat(
	SoPX INT PRIMARY KEY AUTO_INCREMENT,
    MaVTU INT,
    DGXuat FLOAT,
    SLXuat INT,
    FOREIGN KEY (SoPX) REFERENCES PhieuXuat (SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU)
);

CREATE TABLE ChiTietPhieuNhap(
    SoPN INT PRIMARY KEY AUTO_INCREMENT,
    MaVTU INT,
    DGNhap FLOAT,
    SLNhap INT,
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PhieuNhap (SoPN)
);

CREATE TABLE ChiTietDonDatHang(
    SoDH INT PRIMARY KEY AUTO_INCREMENT,
    MaVTU INT,
    FOREIGN KEY (MaVTU) REFERENCES VatTu (MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DonDH (SoDH)
);

CREATE TABLE ThongTin(
    MaNCC INT NOT NULL,
	SoDH INT NOT NULL,
    PRIMARY KEY (MaNCC, SoDH),
    FOREIGN KEY (MaNCC) REFERENCES NhaCC (MaNCC),
    FOREIGN KEY (SoDH) REFERENCES DonDH (SoDH)
);		